### Login (correct username and password pair)
POST /auth/login
Host: {{host}}
Content-Type: application/json; charset=UTF-8

{
  "username": "zihluwang",
  "password": "460215SxkDECN"
}

### Login (incorrect username and password pair)
POST /auth/login
Host: {{host}}
Content-Type: application/json; charset=UTF-8

{
  "username": "zihluwang",
  "password": "460215SxkDEC"
}